name: ml-env

channels:
  - defaults
  - conda-forge

dependencies:
  - python
  - pip

  # default chanel
  - datashader  # fancy plots
  - keras
  - joblib
  - numpy
  - pandas
  - pytables
  - scikit-learn
  - scikit-optimize
  - seaborn

  # conda-forge packages
  - conda-forge:autopep8
  - conda-forge:isort
  - conda-forge:jupyterlab
  - conda-forge:lightgbm
  - conda-forge:nbstripout
  - conda-forge:plotnine 

  - pip:
      git+https://github.com/darenr/scikit-optimize
